---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: voting-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  ingressClassName: nginx
  rules:
  - host: voting-app.sanusibit.me
  - http:
      paths:
      - path: /result(.*)
        pathType: Prefix
        backend:
          service:
            name: result
            port:
              number: 5001
      - path: /vote(.*)
        pathType: Prefix
        backend:
          service:
            name: vote
            port:
              number: 5000
