---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - name: result
        image: dockersamples/examplevotingapp_vote:latest
        ports:
        - containerPort: 80
          name: vote
        env:
        - name: REDIS
          value: "redis.default.svc.cluster.local"
        - name: POSTGRES_HOST
          value: "db.default.svc.cluster.local"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: postgres
        
        
